/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Project, Skill } from '../types';

export const PROJECTS_DATA: Project[] = [
  {
    id: 'p1',
    title: 'OG Username Account "xXTrangXx"',
    titleVi: 'Acc Username OG "xXTrangXx"',
    description: 'Successfully traded a rare OG username Roblox account for 500k Robux. Verified identity, negotiated terms, and completed safe middleman transfer.',
    descriptionVi: 'Trade thành công acc username OG cực hiếm với giá trị 500k Robux. Xác minh danh tính, đàm phán điều khoản và hoàn tất chuyển giao qua middleman an toàn.',
    category: 'trade',
    tags: ['OG Username', 'High Value', 'Safe MM'],
    link: '#',
    cutenessRating: 5,
    iconName: 'Star',
    color: 'from-amber-100 to-orange-200 text-amber-800',
    status: 'completed',
  },
  {
    id: 'p2',
    title: 'Limited Item Collection — x3 ROI',
    titleVi: 'Bộ Sưu Tập Limited — Lời x3',
    description: 'Collected 12 limited Roblox items over 1 month, flipped at the right time and tripled the total investment. Strategic market timing & item value research.',
    descriptionVi: 'Gom 12 item limited trong 1 tháng, chốt đúng thời điểm và thu lời gấp 3. Nghiên cứu thị trường và định thời điểm bán chiến lược.',
    category: 'collector',
    tags: ['Limited Items', 'Market Flip', 'ROI x3'],
    link: '#',
    cutenessRating: 5,
    iconName: 'Gem',
    color: 'from-pink-100 to-rose-200 text-rose-800',
    status: 'completed',
  },
  {
    id: 'p3',
    title: 'Account Appraisal Service',
    titleVi: 'Dịch Vụ Thẩm Định Giá Acc',
    description: 'Provided accurate Roblox account valuation for 50+ clients. Analyzed RAP, inventory, username rarity, badges, and platform trust score.',
    descriptionVi: 'Cung cấp dịch vụ định giá tài khoản Roblox chính xác cho 50+ khách. Phân tích RAP, kho đồ, độ hiếm username, huy hiệu và điểm uy tín.',
    category: 'service',
    tags: ['Appraisal', 'RAP Analysis', '50+ Clients'],
    link: '#',
    cutenessRating: 4,
    iconName: 'ScanSearch',
    color: 'from-teal-100 to-emerald-200 text-teal-800',
    status: 'ongoing',
  },
  {
    id: 'p4',
    title: 'Community Trade Marathon Event',
    titleVi: 'Sự Kiện Trade Marathon Cộng Đồng',
    description: 'Organized a community Roblox trade event with 100+ participants. Managed listings, ensured fair deals, and facilitated 30+ successful swaps in one session.',
    descriptionVi: 'Tổ chức buổi trade Roblox cộng đồng với 100+ người tham gia. Quản lý danh sách, đảm bảo giao dịch công bằng và hỗ trợ 30+ deal thành công trong một buổi.',
    category: 'event',
    tags: ['Community', '100+ Users', 'Event Org'],
    link: '#',
    cutenessRating: 5,
    iconName: 'Users',
    color: 'from-sky-100 to-indigo-200 text-sky-800',
    status: 'completed',
  },
  {
    id: 'p5',
    title: 'Anti-Scam Guide for Traders',
    titleVi: 'Hướng Dẫn Chống Scam Cho Trader',
    description: 'Wrote a comprehensive guide on avoiding Roblox trade scams, read and shared by 1000+ people in the community. Covers fake MM, phishing, and item glitch scams.',
    descriptionVi: 'Viết guide toàn diện về tránh scam khi trade Roblox, được 1000+ người đọc và chia sẻ. Bao gồm fake MM, phishing, và scam lỗi item.',
    category: 'guide',
    tags: ['Anti-Scam', '1000+ Reads', 'Community Guide'],
    link: '#',
    cutenessRating: 4,
    iconName: 'ShieldCheck',
    color: 'from-yellow-100 to-amber-200 text-amber-800',
    status: 'completed',
  },
];

export const SKILLS_DATA: Skill[] = [
  {
    name: 'Account Appraisal (Định Giá)',
    nameVi: 'Định Giá Tài Khoản Roblox',
    level: 95,
    iconName: 'TrendingUp',
    color: 'bg-amber-400',
    category: 'trading',
    cuteLabel: 'Master Appraiser 💎',
    cuteLabelVi: 'Chuyên gia định giá acc 💎',
  },
  {
    name: 'Safe Trade / Anti-Scam',
    nameVi: 'Giao Dịch An Toàn / Chống Scam',
    level: 98,
    iconName: 'ShieldCheck',
    color: 'bg-emerald-400',
    category: 'safety',
    cuteLabel: 'Scam Slayer 🛡️',
    cuteLabelVi: 'Khắc tinh của scammer 🛡️',
  },
  {
    name: 'Trade Server Knowledge',
    nameVi: 'Biết Nhiều Server Trade',
    level: 90,
    iconName: 'Globe',
    color: 'bg-sky-400',
    category: 'community',
    cuteLabel: 'Community Navigator 🌐',
    cuteLabelVi: 'Chuyên gia server cộng đồng 🌐',
  },
  {
    name: 'Rare Items & Robux Valuation',
    nameVi: 'Hiểu Biết Item Hiếm & Giá Robux',
    level: 92,
    iconName: 'Gem',
    color: 'bg-purple-400',
    category: 'trading',
    cuteLabel: 'Limited Item Oracle ✨',
    cuteLabelVi: 'Tiên tri item limited ✨',
  },
  {
    name: 'Account Marketing',
    nameVi: 'Marketing / Quảng Bá Tài Khoản',
    level: 80,
    iconName: 'Megaphone',
    color: 'bg-rose-400',
    category: 'business',
    cuteLabel: 'Hype Generator 📣',
    cuteLabelVi: 'Bậc thầy viral acc 📣',
  },
  {
    name: 'Customer Support',
    nameVi: 'Hỗ Trợ Khách Mua Bán',
    level: 88,
    iconName: 'MessageCircle',
    color: 'bg-pink-400',
    category: 'business',
    cuteLabel: 'Friendly Dealer 💬',
    cuteLabelVi: 'Tư vấn viên thân thiện 💬',
  },
  {
    name: 'Price Negotiation',
    nameVi: 'Đàm Phán Giá (Negotiation)',
    level: 85,
    iconName: 'Handshake',
    color: 'bg-indigo-400',
    category: 'business',
    cuteLabel: 'Deal Closer Pro 🤝',
    cuteLabelVi: 'Bậc thầy chốt deal 🤝',
  },
  {
    name: 'Account Verification',
    nameVi: 'Xác Minh Tài Khoản Thật / Giả',
    level: 97,
    iconName: 'ScanSearch',
    color: 'bg-teal-400',
    category: 'safety',
    cuteLabel: 'Truth Detector 🔍',
    cuteLabelVi: 'Máy phát hiện acc giả 🔍',
  },
];
